[package]
name = "image2array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
egui = "0.18.1"
eframe = "0.18.0"
clipboard = "0.5.0"
emath = "0.18.0"
